name: Timestamp

on:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    timestamp:
        runs-on: ubuntu-latest
        steps:
            - name: Timestamp
              run: echo "the time is $(date)"